//导航
// function showX(obj){obj.src="./img/首页1.png";}function showY(obj){obj.src="./img/首页2.png" }
	function showA(obj){obj.src="./img/1.png";}function showB(obj){obj.src="./img/11.png" }
	function showC(obj){obj.src="./img/2.png";}function showD(obj){obj.src="./img/22.png" }
	function showE(obj){obj.src="./img/3.png";}function showF(obj){obj.src="./img/33.png" }
	function showG(obj){obj.src="./img/4.png";}function showH(obj){obj.src="./img/44.png" }
	function showI(obj){obj.src="./img/5.png";}function showJ(obj){obj.src="./img/55.png" }
	function showK(obj){obj.src="./img/6.png";}function showL(obj){obj.src="./img/66.png" }
	function showM(obj){obj.src="./img/7.png";}function showN(obj){obj.src="./img/77.png" }
	function showO(obj){obj.src="./img/8.png";}function showP(obj){obj.src="./img/88.png" }
	function showQ(obj){obj.src="./img/9.png";}function showR(obj){obj.src="./img/99.png" }
	function showS(obj){obj.src="./img/10.png";}function showT(obj){obj.src="./img/1010.png" }
//小导航
$(function(){
    $('#s1').bind('click',function(){
      $('#s1').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s2').bind('click',function(){
      $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s2').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s3').bind('click',function(){
      $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s4').bind('click',function(){
      $('#s4').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s5').bind('click',function(){
      $('#s5').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s6').bind('click',function(){
      $('#s6').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s7').bind('click',function(){
      $('#s7').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s8').bind('click',function(){
      $('#s8').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#s9').bind('click',function(){
      $('#s9').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#s2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#s7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#s1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#a').bind('click',function(){
      $('#a').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#b').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#c').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#d').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#e').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#b').bind('click',function(){
      $('#b').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#a').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#c').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#d').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#e').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#c').bind('click',function(){
      $('#c').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#b').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#a').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#d').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#e').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#d').bind('click',function(){
      $('#d').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#b').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#c').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#a').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#e').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#e').bind('click',function(){
      $('#e').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#b').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#c').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#d').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#a').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
});
$(function(){
    $('#r1').bind('click',function(){
      $('#r1').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r2').bind('click',function(){
      $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r2').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r3').bind('click',function(){
      $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r4').bind('click',function(){
      $('#r4').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r5').bind('click',function(){
      $('#r5').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r6').bind('click',function(){
      $('#r6').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r7').bind('click',function(){
      $('#r7').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r8').bind('click',function(){
      $('#r8').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#r9').bind('click',function(){
      $('#r9').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r10').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	 $('#r10').bind('click',function(){
      $('#r10').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#r2').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r3').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r4').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r5').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r6').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#r7').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r8').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r9').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#r1').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#h').bind('click',function(){
      $('#h').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#i').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#j').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#k').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#l').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#i').bind('click',function(){
      $('#i').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#h').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#j').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#k').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#l').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#j').bind('click',function(){
      $('#j').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#i').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#h').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#k').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#l').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#k').bind('click',function(){
      $('#k').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#i').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#j').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#h').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#l').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
	$('#l').bind('click',function(){
      $('#l').css({"background-color":"#13c7a9","color":"#fff","border":"none"});
      $('#i').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#j').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
      $('#k').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
	  $('#h').css({"border":"1px solid #ccc","color":"#666","background-color":"#fff"});
    });
});
$(function(){
	$('#a1').bind('click',function(){
      $('#a1').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a11').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a2').bind('click',function(){
      $('#a2').css({"color":"#13c7a9"});
      $('#a1').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a22').show();
      $('#a11').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a3').bind('click',function(){
      $('#a3').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a1').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a33').show();
      $('#a22').hide();
	  $('#a11').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a4').bind('click',function(){
      $('#a4').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a44').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a11').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a5').bind('click',function(){
      $('#a5').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a55').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a11').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a6').bind('click',function(){
      $('#a6').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a66').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a11').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a7').bind('click',function(){
      $('#a7').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a77').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a11').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a8').bind('click',function(){
      $('#a8').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a88').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a11').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a9').bind('click',function(){
      $('#a9').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a99').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a11').hide();
	  $('#a1010').hide();
	  $('#ajj').hide();
    });
	$('#a10').bind('click',function(){
      $('#a10').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#aj').css({"color":"#666"});
	  $('#a1010').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a11').hide();
	  $('#ajj').hide();
    });
	$('#aj').bind('click',function(){
      $('#aj').css({"color":"#13c7a9"});
      $('#a2').css({"color":"#666"});
      $('#a3').css({"color":"#666"});
	  $('#a4').css({"color":"#666"});
	  $('#a5').css({"color":"#666"});
	  $('#a6').css({"color":"#666"});
	  $('#a7').css({"color":"#666"});
	  $('#a8').css({"color":"#666"});
	  $('#a9').css({"color":"#666"});
	  $('#a10').css({"color":"#666"});
	  $('#a1').css({"color":"#666"});
	  $('#ajj').show();
      $('#a22').hide();
	  $('#a33').hide();
	  $('#a44').hide();
	  $('#a55').hide();
	  $('#a66').hide();
	  $('#a77').hide();
	  $('#a88').hide();
	  $('#a99').hide();
	  $('#a1010').hide();
	  $('#a11').hide();
    });
});
$(function(){
	$('#b1').bind('click',function(){
      $('#b1').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb1').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b2').bind('click',function(){
      $('#b2').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb2').show();
      $('#bb1').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b3').bind('click',function(){
      $('#b3').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb3').show();
      $('#bb2').hide();
	  $('#bb1').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b4').bind('click',function(){
      $('#b4').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb4').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb1').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b5').bind('click',function(){
      $('#b5').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb5').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb1').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b6').bind('click',function(){
      $('#b6').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb6').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb1').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b7').bind('click',function(){
      $('#b7').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb7').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb1').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b8').bind('click',function(){
      $('#b8').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb8').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb1').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b9').bind('click',function(){
      $('#b9').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb9').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb1').hide();
	  $('#bb10').hide();
	  $('#bb11').hide();
    });
	$('#b10').bind('click',function(){
      $('#b10').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b11').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb10').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb1').hide();
	  $('#bb11').hide();
    });
	$('#b11').bind('click',function(){
      $('#b11').css({"color":"#13c7a9","border-bottom":"2px solid #13c7a9"});
      $('#b2').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
      $('#b3').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b4').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b5').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b6').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b7').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b8').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b9').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b10').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#b1').css({"color":"#666","border-bottom":"2px solid #f3ecd0"});
	  $('#bb11').show();
      $('#bb2').hide();
	  $('#bb3').hide();
	  $('#bb4').hide();
	  $('#bb5').hide();
	  $('#bb6').hide();
	  $('#bb7').hide();
	  $('#bb8').hide();
	  $('#bb9').hide();
	  $('#bb10').hide();
	  $('#bb1').hide();
    });
});
$(function(){
	$('#c1').bind('click',function(){
      $('#c1').css({"color":"#13c7a9"});
      $('#c2').css({"color":"#666"});
      $('#c3').css({"color":"#666"});
	  $('#c11').show();
      $('#c22').hide();
	  $('#c33').hide();
    });
	$('#c2').bind('click',function(){
      $('#c2').css({"color":"#13c7a9"});
      $('#c1').css({"color":"#666"});
      $('#c3').css({"color":"#666"});
	  $('#c22').show();
      $('#c11').hide();
	  $('#c33').hide();
    });
	$('#c3').bind('click',function(){
      $('#c3').css({"color":"#13c7a9"});
      $('#c2').css({"color":"#666"});
      $('#c1').css({"color":"#666"});
	  $('#c33').show();
      $('#c22').hide();
	  $('#c11').hide();
    });
});
$(function(){
	$('#d1').bind('click',function(){
      $('#d1').css({"background-color":"#13c7a9","color":"#fff"});
      $('#d2').css({"background-color":"#fff","color":"#333"});
      $('#d3').css({"background-color":"#fff","color":"#333"});
	  $('#d11').show();
      $('#d22').hide();
	  $('#d33').hide();
    });
	$('#d2').bind('click',function(){
      $('#d2').css({"background-color":"#13c7a9","color":"#fff"});
      $('#d1').css({"background-color":"#fff","color":"#333"});
      $('#d3').css({"background-color":"#fff","color":"#333"});
	  $('#d22').show();
      $('#d11').hide();
	  $('#d33').hide();
    });
	$('#d3').bind('click',function(){
      $('#d3').css({"background-color":"#13c7a9","color":"#fff"});
      $('#d2').css({"background-color":"#fff","color":"#333"});
      $('#d1').css({"background-color":"#fff","color":"#333"});
	  $('#d33').show();
      $('#d22').hide();
	  $('#d11').hide();
    });
});